- name: MySQL Setup
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.pavansai.online -uroot -pRoboShop@1 < /app/schema/{{component}}.sql