- name: Installing Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: latest

- name: App Pre-Requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Schema Setup
  ansible.builtin.import_tasks: mongodb-schema.yml
  when: schema is defined

- name: Systemd Setup
  ansible.builtin.import_tasks: systemd-setup.yml

